# Metric prefix to show metrics in one tier (HIGHLY RECOMMENDED)
# Please follow the Metric Path section of https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java for instructions on retrieving the tier ID
#metricPrefix: "Server|Component:<TIER_ID>|Log Monitor|"

#Metric Prefix when SIM is enabled"
#metricPrefix: "Custom Metrics|Murex Monitor|"

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricPathReplacements:
- replace: ":"
  replaceWith: ";"
- replace: "|"
  replaceWith: "="
- replace: ","
  replaceWith: "#"

#metricCharacterReplacer:
#  - replace: ":"
#    replaceWith: ";"
#  - replace: "\\|"
#    replaceWith: "#"
#  - replace: "\\,"
#    replaceWith: "#"

# Number of concurrent threads
numberOfThreads: 20

#Thread timeout in seconds
threadTimeOut: 60

sendDataToEventsService: true

# This field contains the various parameters required to initiate a connection and send data to the AppDynamics Events Service.
eventsServiceParameters:
  host: "<analytics endpoint>"
  port: 443
  globalAccountName: "<global account name>"
  eventsApiKey: "<api key>"
  useSSL: true

#You can leave username empty if no proxy user is required
proxy:
  uri: ""
  username: ""

#example proxy settings:
#uri: "http://localhost:8080"


# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
controllerInfo:
  controllerHost: "" # -Dappdynamics.controller.hostName
  controllerPort: 8090 # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName

encryptionKey: "abcd"
scriptPath: "/u01/app/murex_app"
command: "./launchmxj.app -s"

eventsSchemaDefinition: '{
        "schema" : {
        "nodeName": "string", 
        "serviceName": "string", 
        "processId": "string", 
        "cpuTime": "string", 
        "startTime": "string" 
        }
        }'
